export default {
    SOMETHING_WENT_WRONG: "Something went wrong , server error",
    USER_ALREADY_EXIST:"User Already Exists",
    AUTHORIZATION_ERROR:"Authorization failed",
    OTP_VERIFIED:"Otp verified successfully",
    OTP_NOT_FOUND:"Otp not found",
    OTP_EXPIRED:"Otp is expired",
    OTP_NOT_MATCH:"Otp did not match",
    LOGIN_FAILED:"Invalid email or password",
    USER_NOT_FOUND:"User not found",
    OTP_SENT_SUCCESSFULL:"Otp sent successfully",
    OTP_SENT_FAILED:"Failed to send Otp",
    OTP_RESENT_SUCCESSFULL:"Otp resent successfully",
    EMAIL_REQUIRED:"Email is required",
    THEME_NOT_ADDED:"Theme is not added",
    NEW_THEME_ABSENT:"New theme is not present",
    CURRENT_THEME_ABSENT:"Current theme is not present",
    FILES_EMPTY:"No files found",
    USER_ID_REQUIRED:"UserId is required",
    PASSWORD_RESET_SUCCESS:"Password reset successfully",
    PASSWORD_RESET_FAILED:"Failed to reset password",
    PASSWORD_NOT_MATCH:"Password did not match",
    UPDATE_PROFILE_FAILED:"Failed to update user profile",
    USER_THEME_ABSENT:"Failed to get user theme",
    CHATBOT_ID_REQUIRED:"ChatbotId is required",
}